### ISSUE TITLE
Exception has occurred: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by petermetz** [epoberezkin/json-schema-traverse#43]
If an OpenAPI schema definition contains cycles, then the traversal fails with the error and call stackbelow:

```sh
Exception has occurred: RangeError: Maximum call stack size exceeded
  at _traverse ([/*****/node_modules/ajv/node_modules/json-schema-traverse/index.js:63:19]())
    at _traverse ([/*****/node_modules/ajv/node_modules/json-schema-traverse/index.js:79:9]())
    at _traverse ([/*****/node_modules/ajv/node_modules/json-schema-traverse/index.js:76:13]())
    at _traverse ([/*****/node_modules/ajv/node_modules/json-schema-traverse/index.js:79:9]())
    at _traverse ([/*****/node_modules/ajv/node_modules/json-schema-traverse/index.js:76:13]())
    at _traverse ([/*****/node_modules/ajv/node_modules/json-schema-traverse/index.js:79:9]())
    at _traverse ([/*****/node_modules/ajv/node_modules/json-schema-traverse/index.js:76:13]())
    at _traverse ([/*****/node_modules/ajv/node_modules/json-schema-traverse/index.js:79:9]())
    at _traverse ([/*****/node_modules/ajv/node_modules/json-schema-traverse/index.js:76:13]())
    at _traverse ([/*****/node_modules/ajv/node_modules/json-schema-traverse/index.js:79:9]())
```

**Comment by epoberezkin** [comment]
What do you mean by cycles? If these are JavaScript objects with cycles they are not supported - you need to use $ref instead.

In any case, please submit a minimal example to reproduce - as is, it’s impossible to say what is wrong.

**Comment by petermetz** [comment]
> What do you mean by cycles? If these are JavaScript objects with cycles they are not supported - you need to use $ref instead.
> 
> In any case, please submit a minimal example to reproduce - as is, it’s impossible to say what is wrong.

@epoberezkin Apologies for not providing further details upfront. 
Here's the openapi spec [1] that we are validating through the npm package `express-openapi-validator` (which uses `ajv` which uses `json-schema-traverse`)

You can see that the `JvmType` and the `JvmObject` schema components are referencing each other, but one of the references is optional so an infinite loop is not a problem with regards the reference chain.

I know that this is still not a fully self contained, executable reproduction code, I can provide that a few days from now hopefully if needed, just let me know and I'll put the extra work in.

1: https://github.com/hyperledger/cactus/blob/main/packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json#L180

[1]: https://github.com/hyperledger/cactus/blob/main/packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json#L180

**Comment by epoberezkin** [comment]
json-schema-traverse doesn’t resolve references, it simply iterates the object structure. So it shouldn’t, in theory, go into endless loop because of mutual references ($refs) in the schema, and such references are supported by ajv. I suspect you have some library there that dereferences $refs into plain objects, to produce a flattened schema without references, and in this case it produces a cyclic JavaScript object…

**Comment by petermetz** [comment]
@epoberezkin While creating the minimal example, I realized that the issue was exactly as you suspected. The `express-openapi-validator` package resolves the $refs into JS object references in the schema before passing it down to `json-schema-traverse` for traversal and that's why it chokes on it. I understand that letting it work with JS object references instead of $refs is out of scope so closing this one and sorry for taking up your time with this!
